"""add storage key to documents

Revision ID: c47defccc82e
Revises: 3e5f195647f1
Create Date: 2026-09-18 11:14:06.650161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47defccc82e'
down_revision: Union[str, Sequence[str], None] = '3e5f195647f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'documents', ['storage_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
